### ISSUE TITLE
route not found 404

### ISSUE THREAD

**Issue by ruby261** [openware/baseapp#139]
my app.yml images, When I try other images it won't even compile. This works but gives error as below And on the home page it says route not fund.

```
images:
  peatio: quay.io/openware/peatio:2.3.55
  barong: quay.io/openware/barong:2.3.47
  frontend: 3cf325445575
 # frontend: quay.io/openware/baseapp:2.3.26 # Check on quay.io/openware/baseapp for latest tags
  tower: quay.io/openware/tower:2.3.137
  postmaster: quay.io/openware/postmaster:2.3.5
```

`www.domain.com/:1 Error in event handler: TypeError: Cannot read property 'notice_1' of undefined
    at parseMessage (chrome-extension://dbfipcjecamggjfabeaclacjoohfjhhn/js/content/content.js:8886:51)
/api/v2/barong/identity/configs:1 Failed to load resource: the server responded with a status of 404 ()
/api/v2/barong/resource/users/me:1 Failed to load resource: the server responded with a status of 401 ()`
